<?php

namespace AppBundle\Repository;

/**
 * BanderasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanderasRepository extends \Doctrine\ORM\EntityRepository
{
}
