<?php

namespace AppBundle\Repository;

/**
 * CategoriapaisesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriapaisesRepository extends \Doctrine\ORM\EntityRepository
{
}
