<?php

namespace AppBundle\Repository;

/**
 * CategoriaconsularRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaconsularRepository extends \Doctrine\ORM\EntityRepository
{
}
