<?php

namespace AppBundle\Repository;

/**
 * CategoriapasaporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriapasaporteRepository extends \Doctrine\ORM\EntityRepository
{
}
