<?php

namespace AppBundle\Repository;

/**
 * CodigosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodigosRepository extends \Doctrine\ORM\EntityRepository
{
}
