<?php

namespace AppBundle\Repository;

/**
 * ConsuladosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsuladosRepository extends \Doctrine\ORM\EntityRepository
{
}
