<?php

namespace AppBundle\Repository;

/**
 * EdisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdisonRepository extends \Doctrine\ORM\EntityRepository
{
}
