<?php

namespace AppBundle\Repository;

/**
 * InfopaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfopaisRepository extends \Doctrine\ORM\EntityRepository
{
}
