<?php

namespace AppBundle\Repository;

/**
 * MapasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapasRepository extends \Doctrine\ORM\EntityRepository
{
}
