<?php

namespace AppBundle\Repository;

/**
 * PaisesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaisesRepository extends \Doctrine\ORM\EntityRepository
{
}
