<?php

namespace AppBundle\Repository;

/**
 * PasaporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasaporteRepository extends \Doctrine\ORM\EntityRepository
{
}
