<?php

namespace AppBundle\Repository;

/**
 * RedconsularRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedconsularRepository extends \Doctrine\ORM\EntityRepository
{
}
