<?php

namespace AppBundle\Repository;

/**
 * RequisitosviajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequisitosviajeRepository extends \Doctrine\ORM\EntityRepository
{
}
